name: Terrafrom Workflow-reusable

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Validating:
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: dev
      terraform_directory: ""
      artifact-name: art-1
    secrets: inherit
      
  Prod:
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: prod
      terraform_directory: ""
      artifact-name: art-1
    secrets: inherit
    