name: caller

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_dispatch:
    # inputs:
    #   artifact-name:
    #     required: true
    #     type: string

env:
  artifactname: 'art-1'

# on: push

jobs:
  build:
    
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: devop
      terraform_directory: ""
      artifact-name: ${{ env.artifactname }}
    secrets: inherit