name: container terraform
on: push
jobs:
  Build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
  Validating:
    runs-on: ubuntu-latest
    name: Validating the Terraform files
    if: github.event_name == 'pull_request' || github.event.ref == 'refs/heads/main'
    needs: [Build]
    container:
      image: ubuntu:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  DeployProd:
    runs-on: ubuntu-latest
    name: Deploy to Production
    if: github.event.ref == 'refs/heads/main'
    needs: [Validating]
    container:
      image: ubuntu:latest
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    environment: 
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          #terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform code
        run: terraform validate

        #     # - name: Plan Terraform changes
  #     #   run: terraform plan
      
  #     # - name: Plan Terraform changes
  #     #   run: terraform apply --auto-approve