name: self-service-call-payload

on:
  push:
  repository_dispatch:

jobs:
  run_if:
    #if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.worflowname2 }}
        run: echo $MESSAGE