name: self-service-call-payload

on:
  repository_dispatch:

jobs:
  run_if_failure:
    #if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.workflow2_name }}
        run: echo $MESSAGE