name: workflow-to-workflow

on: [repository_dispatch]

jobs:
  build:
    uses: vinayprakash893/azure-terraform-actions-reusable/.github/workflows/build.yaml@main
    with:
      environment: dev
      terraform_directory: ""
      artifact-name: 'art-vny-1'
    secrets: inherit